apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o6oaqzp5h-python 
  janus-idp.io/tekton: o6oaqzp5h-python
  backstage.io/kubernetes-id: o6oaqzp5h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o6oaqzp5h-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  